"""
PCA analysis of hidden states from connectome RNN checkpoint runs.

Loads .npy files containing hidden states (shape: T x N) and performs
PCA to visualize the neural trajectories in reduced dimensions.
The .npy files are generated by run_connectome_rnn_checkpoint.py with
save_hidden_states=True.
"""

import os
import glob
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# ---- Global plot style ----
plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams["font.size"] = 24

# ---- Configuration ----
NPY_DIR = r"D:\Benquan\OneDrive MSState\OneDrive - Mississippi State University\Publications\IROS2026\materials\PCA\connectome2"

# Display labels for each file (basename without extension)
LABEL_MAP = {
    "full_vision": "Full Vision",
    "left_eye_only": "Left Eye Only",
    "right_eye_only": "Right Eye Only",
    "total_blind": "Total Blind",
}

# Colors for each condition
COLOR_MAP = {
    "full_vision": "#2196F3",       # blue
    "left_eye_only": "#4CAF50",     # green
    "right_eye_only": "#FF9800",    # orange
    "total_blind": "#F44336",       # red
}


def load_hidden_states(npy_dir: str) -> dict:
    """Load all top-level .npy and .npz files from *npy_dir*.

    For .npy files the array is used directly (expected shape T x N).
    For .npz files every array inside is flattened to 2-D (T, features)
    and then concatenated along axis=1 to produce a single (T, N) matrix.

    Returns
    -------
    data : dict[str, np.ndarray]
        Mapping from stem name (e.g. 'full_vision') to array of shape (T, N).
    """
    npy_files = sorted(glob.glob(os.path.join(npy_dir, "*.npy")))
    npz_files = sorted(glob.glob(os.path.join(npy_dir, "*.npz")))
    all_files = npy_files + npz_files
    if not all_files:
        raise FileNotFoundError(f"No .npy/.npz files found in {npy_dir}")

    data = {}
    for fpath in all_files:
        stem = os.path.splitext(os.path.basename(fpath))[0]
        if fpath.endswith(".npz"):
            npz = np.load(fpath)
            parts = []
            for key in sorted(npz.files):
                a = npz[key]                       # (T, ...) arbitrary shape
                T = a.shape[0]
                parts.append(a.reshape(T, -1))     # flatten to (T, features)
            arr = np.concatenate(parts, axis=1)     # (T, N)
            print(f"[io] Loaded {stem} (.npz, {len(npz.files)} arrays): "
                  f"shape={arr.shape}, dtype={arr.dtype}")
        else:
            arr = np.load(fpath)
            print(f"[io] Loaded {stem}: shape={arr.shape}, dtype={arr.dtype}")
        data[stem] = arr
    return data


def analyze_hidden_states(npy_dir: str = NPY_DIR) -> None:
    """Perform PCA on hidden-state trajectories and plot the results.

    Each .npy file is expected to have shape (T, N) where T is timesteps
    and N is the number of neurons.  A joint PCA is fitted on the
    concatenated data so that all conditions share the same principal axes.
    """
    # 1. Load data
    data = load_hidden_states(npy_dir)

    # 2. Concatenate all hidden states for joint PCA fitting
    all_states = np.concatenate(list(data.values()), axis=0)  # (sum_T, N)
    print(f"[pca] Joint data matrix: {all_states.shape}")

    pca = PCA(n_components=10)
    pca.fit(all_states)
    print(f"[pca] Explained variance ratio (PC1-10): {pca.explained_variance_ratio_}")

    # 3. Transform each condition separately (all 10 PCs)
    projected_10 = {}
    for stem, arr in data.items():
        projected_10[stem] = pca.transform(arr)  # (T, 10)

    # Keep only first 3 PCs for the trajectory plots
    projected = {stem: proj[:, :3] for stem, proj in projected_10.items()}

    # ---- Plot 1: 2-D PCA trajectories (PC1 vs PC2) ----
    fig, ax = plt.subplots(figsize=(8, 6))
    for stem, proj in projected.items():
        label = LABEL_MAP.get(stem, stem)
        color = COLOR_MAP.get(stem, None)
        ax.plot(proj[:, 0], proj[:, 1], linewidth=1.2, alpha=0.85,
                label=label, color=color)
        # Mark start and end
        ax.scatter(proj[0, 0], proj[0, 1], marker='o', s=60, color=color,
                   edgecolors='k', zorder=5)
        ax.scatter(proj[-1, 0], proj[-1, 1], marker='X', s=80, color=color,
                   edgecolors='k', zorder=5)

    ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
    ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
    # ax.set_title("PCA of Connectome RNN Hidden States")
    # ax.legend(loc="best")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()

    # # ---- Plot 2: PC components over time ----
    # fig2, axes = plt.subplots(3, 1, figsize=(10, 7), sharex=True)
    # for pc_idx, ax2 in enumerate(axes):
    #     for stem, proj in projected.items():
    #         label = LABEL_MAP.get(stem, stem)
    #         color = COLOR_MAP.get(stem, None)
    #         ax2.plot(proj[:, pc_idx], linewidth=1.0, alpha=0.85,
    #                  label=label, color=color)
    #     ax2.set_ylabel(f"PC{pc_idx+1}")
    #     ax2.grid(True, alpha=0.3)
    #     if pc_idx == 0:
    #         ax2.legend(loc="best", fontsize=8)
    # axes[-1].set_xlabel("Time Step")
    # axes[0].set_title("Principal Components Over Time")
    # fig2.tight_layout()

    # ---- Plot 2b: PC1 & PC2 over time as 3-D trajectory ----
    fig2b = plt.figure(figsize=(9, 7))
    ax2b = fig2b.add_subplot(111, projection='3d')

    # Preliminary pass: draw invisible lines to establish axis limits
    for stem, proj in projected.items():
        t = np.arange(proj.shape[0])
        ax2b.plot(t, proj[:, 0], proj[:, 1], alpha=0.0)

    ax2b.set_xlabel("Time Step", labelpad=20)
    ax2b.set_ylabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)", labelpad=20)
    ax2b.set_zlabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)", labelpad=20)

    # Wall projections (drawn first so they layer below main curves)
    t_min, t_max = ax2b.get_xlim()
    pc1_min, pc1_max = ax2b.get_ylim()
    pc2_min, pc2_max = ax2b.get_zlim()
    proj_alpha = 0.5
    for stem, proj in projected.items():
        color = COLOR_MAP.get(stem, None)
        t = np.arange(proj.shape[0])
        # XY floor (z = pc2_min): Time vs PC1
        ax2b.plot(t, proj[:, 0], pc2_min, linewidth=0.8, alpha=proj_alpha, color=color, linestyle='--')
        ax2b.scatter(t[0], proj[0, 0], pc2_min, marker='o', s=60, color=color, edgecolors='k', alpha=proj_alpha)
        ax2b.scatter(t[-1], proj[-1, 0], pc2_min, marker='s', s=80, color=color, edgecolors='k', alpha=proj_alpha)
        # XZ back wall (y = pc1_max): Time vs PC2
        ax2b.plot(t, pc1_max, proj[:, 1], linewidth=0.8, alpha=proj_alpha, color=color, linestyle='--')
        ax2b.scatter(t[0], pc1_max, proj[0, 1], marker='o', s=60, color=color, edgecolors='k', alpha=proj_alpha)
        ax2b.scatter(t[-1], pc1_max, proj[-1, 1], marker='s', s=80, color=color, edgecolors='k', alpha=proj_alpha)
        # # YZ side wall (x = t_min): PC1 vs PC2
        # ax2b.plot(t_min, proj[:, 0], proj[:, 1], linewidth=0.8, alpha=proj_alpha, color=color)

    # Main 3-D curves (drawn after projections so they layer on top)
    for stem, proj in projected.items():
        label = LABEL_MAP.get(stem, stem)
        color = COLOR_MAP.get(stem, None)
        t = np.arange(proj.shape[0])
        ax2b.plot(t, proj[:, 0], proj[:, 1], linewidth=1.5,
                  alpha=1.0, label=label, color=color)
        ax2b.scatter(t[0], proj[0, 0], proj[0, 1], marker='o', s=60,
                     color=color, edgecolors='k', zorder=5)
        ax2b.scatter(t[-1], proj[-1, 0], proj[-1, 1], marker='s', s=80,
                     color=color, edgecolors='k', zorder=5)

    fig2b.tight_layout()

    # # ---- Plot 3: 3-D PCA trajectories ----
    # fig3 = plt.figure(figsize=(9, 7))
    # ax3 = fig3.add_subplot(111, projection='3d')
    # for stem, proj in projected.items():
    #     label = LABEL_MAP.get(stem, stem)
    #     color = COLOR_MAP.get(stem, None)
    #     ax3.plot(proj[:, 0], proj[:, 1], proj[:, 2], linewidth=1.0,
    #              alpha=1.0, label=label, color=color)
    #     ax3.scatter(proj[0, 0], proj[0, 1], proj[0, 2], marker='o', s=60,
    #                 color=color, edgecolors='k', zorder=5)
    #     ax3.scatter(proj[-1, 0], proj[-1, 1], proj[-1, 2], marker='X', s=80,
    #                 color=color, edgecolors='k', zorder=5)

    # ax3.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)", labelpad=20)
    # ax3.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)", labelpad=20)
    # ax3.set_zlabel(f"PC3 ({pca.explained_variance_ratio_[2]*100:.1f}%)", labelpad=20)
    # # ax3.set_title("3-D PCA of Connectome RNN Hidden States")
    # # ax3.legend(loc="best")

    # # Wall projections for Plot 3
    # pc1_min3, pc1_max3 = ax3.get_xlim()
    # pc2_min3, pc2_max3 = ax3.get_ylim()
    # pc3_min3, pc3_max3 = ax3.get_zlim()
    # for stem, proj in projected.items():
    #     color = COLOR_MAP.get(stem, None)
    #     # XY floor (z = pc3_min): PC1 vs PC2
    #     ax3.plot(proj[:, 0], proj[:, 1], pc3_min3, linewidth=0.8, alpha=proj_alpha, color=color)
    #     # XZ back wall (y = pc2_max): PC1 vs PC3
    #     ax3.plot(proj[:, 0], pc2_max3, proj[:, 2], linewidth=0.8, alpha=proj_alpha, color=color)
    #     # YZ side wall (x = pc1_min): PC2 vs PC3
    #     ax3.plot(pc1_min3, proj[:, 1], proj[:, 2], linewidth=0.8, alpha=proj_alpha, color=color)

    # fig3.tight_layout()

    # ---- Plot: Bar chart of average PCA distance to 1st curve ----
    stems = list(data.keys())  # sorted order from glob
    ref_stem = stems[0]        # 1st curve is the reference
    ref_proj = projected_10[ref_stem]  # (T, 10)

    bar_labels = []
    bar_means = []
    bar_stds = []
    for stem in stems[1:]:
        other_proj = projected_10[stem]  # (T, 10)
        # Pointwise Euclidean distance in 10-D PCA space
        min_T = min(ref_proj.shape[0], other_proj.shape[0])
        dists = np.linalg.norm(ref_proj[:min_T] - other_proj[:min_T], axis=1)
        bar_labels.append(LABEL_MAP.get(stem, stem))
        bar_means.append(np.mean(dists))
        bar_stds.append(np.std(dists))

    fig_bar, ax_bar = plt.subplots(figsize=(6, 5))
    x_pos = np.arange(len(bar_labels))
    bar_colors = [COLOR_MAP.get(stems[i + 1], None) for i in range(len(bar_labels))]
    ax_bar.bar(x_pos, bar_means, yerr=bar_stds, capsize=6,
               color=bar_colors, edgecolor='k', width=0.5, alpha=0.85)
    ax_bar.set_xticks(x_pos)
    ax_bar.set_xticklabels(bar_labels)
    ax_bar.set_ylabel("Euclidean Distance (10 PCs)")
    ax_bar.set_title(f"Avg Distance to {LABEL_MAP.get(ref_stem, ref_stem)}")
    ax_bar.grid(True, alpha=0.3, axis='y')
    fig_bar.tight_layout()

    plt.show()


if __name__ == "__main__":
    analyze_hidden_states()